version: "3.1"
services:
  node:
    build: .
    working_dir: /app
    container_name: lgbt_tech
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    expose:
      - 3000
    command: "npm run dev"
